<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Order.Api</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Order.Application\Order.Application.csproj"/>
        <ProjectReference Include="..\Order.Infrastructure\Order.Infrastructure.csproj"/>
        <ProjectReference Include="..\..\..\Shared\Shared.Observability\Shared.Observability.csproj"/>
        <ProjectReference Include="..\..\..\Shared\Shared.Web\Shared.Web.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Asp.Versioning.Http"/>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore"/>
        <PackageReference Include="NSwag.ApiDescription.Client">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Scalar.AspNetCore"/>
        <PackageReference Include="Serilog.AspNetCore"/>
        <PackageReference Include="Serilog.Enrichers.Environment"/>
        <PackageReference Include="Serilog.Enrichers.Process"/>
        <PackageReference Include="Serilog.Enrichers.Thread"/>
        <PackageReference Include="Serilog.Sinks.Console"/>
        <PackageReference Include="Serilog.Sinks.File"/>
    </ItemGroup>

    <ItemGroup>
        <OpenApiReference Include="Endpoints/Orders/V1/Contracts/orders-management.yaml"
                          Namespace="Order.Api.Endpoints.Orders.V1.Commands.DTOs"
                          OutputPath="Endpoints/Orders/V1/Commands/DTOs/OrderCommandsGenerated.g.cs"
                          CodeGenerator="NSwagCSharp">
            <Options>/GenerateClientClasses:false /GenerateClientInterfaces:false /GenerateDtoTypes:true /JsonLibrary:SystemTextJson /GenerateDefaultValues:true /GenerateNullableReferenceTypes:true /UseBaseUrl:false /DateType:System.DateTimeOffset /DateTimeType:System.DateTimeOffset /ArrayType:System.Collections.Generic.ICollection /ArrayInstanceType:System.Collections.Generic.List /ExcludedTypeNames:ProblemDetails</Options>
        </OpenApiReference>

        <OpenApiReference Include="Endpoints/Orders/V1/Contracts/order-query.yaml"
                          Namespace="Order.Api.Endpoints.Orders.V1.Queries.DTOs"
                          OutputPath="Endpoints/Orders/V1/Queries/DTOs/OrderQueriesGenerated.g.cs"
                          CodeGenerator="NSwagCSharp">
            <Options>/GenerateClientClasses:false /GenerateClientInterfaces:false /GenerateDtoTypes:true /JsonLibrary:SystemTextJson /GenerateDefaultValues:true /GenerateNullableReferenceTypes:true /UseBaseUrl:false /DateType:System.DateTimeOffset /DateTimeType:System.DateTimeOffset /ArrayType:System.Collections.Generic.ICollection /ArrayInstanceType:System.Collections.Generic.List /ExcludedTypeNames:ProblemDetails</Options>
        </OpenApiReference>
    </ItemGroup>

</Project>
